# Generated by Django 4.0.5 on 2024-02-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='url',
            table='url',
        ),
    ]
